/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/Landing/About.vue')['default']
    BlogPosts: typeof import('./components/Blog/BlogPosts.vue')['default']
    CTA: typeof import('./components/Landing/CTA.vue')['default']
    FlyoutMenuSingle: typeof import('./components/Menu/FlyoutMenuSingle.vue')['default']
    Footer: typeof import('./components/Menu/Footer.vue')['default']
    Hero: typeof import('./components/Landing/Hero.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
